version: '2'
services:
    paypark-app:
        image: paypark
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://paypark-mysql:3306/paypark?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    paypark-mysql:
        extends:
            file: mysql.yml
            service: paypark-mysql
